### ISSUE TITLE
missing '.' after this belief

### ISSUE THREAD

**Issue by Mrmichelerocha** [niklasf/pyson#13]
Hi, I'm new to programming for agents and I really want to integrate python into my project, but I get this error when I try to run the sample communication codes.

I already tried to put the '.' but it won't. I don't know if I'm trying to compile the wrong code, but none will.

What can it be?

![image](https://user-images.githubusercontent.com/93664169/205754711-bb428b0f-5ff7-4375-81ca-660608fc1a4f.png)

**Comment by niklasf** [comment]
Hi. `python -m agentspeak` is used to directly run standalone `.asl` files:

```sh
python -m agentspeak examples/hello_world.asl
```

`examples/communication/env.py` is a normal Python script that uses agentspeak as a library, so you can just run it directly:

```
python examples/communication/env.py
```
