### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by javipalanca** [niklasf/pyson#8]
Hi.
Are you planning to publish pyson as a package at PyPI?
There is already a package called pyson at PyPI, so it would be  necessary to publish this with another name (pyson-agentspeak, pyson-asl...)

I can help, if you agree, with the steps to make pyson easily installable and prepare it for publication. I usually follow the python package structure proposed by @audreyr at https://github.com/audreyr/cookiecutter-pypackage, which prepares it for PyPI publication, Travis CI tests, documentation at readthedocs, etc.

I can make a Pull Request with some of these changes if you agree. Let me know.

**Comment by niklasf** [comment]
Hi @javipalanca. Sure, I think that could be useful. `agentspeak` would be a fine package name.

**Comment by javipalanca** [comment]
Great. I'll make the Pull Request ASAP.

**Comment by javipalanca** [comment]
> Hi @javipalanca. Sure, I think that could be useful. `agentspeak` would be a fine package name.

Just a final question. Your where meaning to name the PyPI package `agentspeak` or `pyson-agentspeak`?

**Comment by niklasf** [comment]
Let's do `agentspeak` on PyPI (and I'll rename the repository to `python-agentspeak` on GitHub).

**Comment by javipalanca** [comment]
also the name of the package? So the imports change from `import pyson` to `import agentspeak`

**Comment by javipalanca** [comment]
Pull Request  number #9 made.
